language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.12

# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.yarn
    - ~/.cache
  # install dependencies and check that Cypress can run
  override:
    - yarn ci
    - yarn run cy:verify

install:
  - sudo apt-get update
  - sudo apt-get install jq
before_script:
  - mkdir local
  - cd local
  - jq -n --arg TOKEN '{"Auth-Token":$TOKEN}' > token.json
script:
  # start server in the background and run all Cypress tests and record on the dashboard
  - yarn add parcel-bundler --dev
  - yarn start && yarn test --record
  
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  # this avoids flake in Travis jobs
  - kill $(jobs -p) || true